### ISSUE TITLE
node server js problem

### ISSUE THREAD

**Issue by vino6665** [ismailraju/video-conference-webrtc-nodejs#3]
when run the node serer js ..commend getting folwoing error

internal/fs/utils.js:230
    throw err;
    ^

Error: ENOENT: no such file or directory, open 'D:/C DRIVE/apache-tomcat-8.5.34SSL/webapps/peerconnection/munge-sdp/key.pem'
    at Object.openSync (fs.js:458:3)
    at Object.readFileSync (fs.js:360:35)
    at Object.<anonymous> (C:\Users\Yuvaraj Sabapathi\Desktop\vc\server.js:17:21)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: 'D:/C DRIVE/apache-tomcat-8.5.34SSL/webapps/peerconnection/munge-sdp/key.pem'

**Comment by alireza5014** [comment]
remove node_modules and run this command:
npm install

**Comment by Zw1d** [comment]
You have to create your own certificate/key.
Change `'D:/C DRIVE/apache-tomcat-8.5.34SSL/webapps/peerconnection/munge-sdp/key.pem'`)
to 
`key.pem`
and the other path to `cert.pem`
Generate certs with this:
`openssl req -x509 -newkey rsa:4096 -keyout key.pem -out cert.pem -days 365-nodes`
